# Generated by Django 3.1.2 on 2020-10-28 17:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.nameFile),
        ),
    ]
