# Generated by Django 3.1.2 on 2020-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201112_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileImage',
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=256),
        ),
    ]
